version: '3.8'

volumes:
    public-storage:
    mysql-database:

services:
    php:
        env_file: ${PHP_ENV_FILE_PATH}
    php-cron:
        env_file: ${PHP_ENV_FILE_PATH}
    php-worker:
        env_file: ${PHP_ENV_FILE_PATH}
    nginx:
        env_file: ${NGINX_ENV_FILE_PATH}
        ports:
            - "${NGINX_CONTAINER_PORT}:80"
    mysql:
        image: mysql:5.7.22
        tty: true
        env_file: ${MYSQL_ENV_FILE_PATH}
        volumes:
            - "mysql-database:/var/lib/mysql"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 5s
            timeout: 10s
            retries: 10
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: ${PHPMYADMIN_ENV_FILE_PATH}
        ports:
            - "${PHPMYADMIN_CONTAINER_PORT}:80"
    redis:
        image: redis:4.0
        command: [ "redis-server", "--bind", "0.0.0.0", "--port", "6379" ]
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]